### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'localeCompare' of undefined

### ISSUE THREAD

**Issue by bwood1** [hpcc-systems/Visualization#2221]
When clicking on a driving widget that has a range filter the below JS exception is thrown.

```
Uncaught (in promise) TypeError: Cannot read property 'localeCompare' of undefined
    at Filter.matches (http://172.23.42.86:8081/js/Visualization/src/marshaller/HipieDDL.js:1473:29)
    at http://172.23.42.86:8081/js/Visualization/src/other/Comms.js:945:56
    at Array.filter (native)
    at filterResults (http://172.23.42.86:8081/js/Visualization/src/other/Comms.js:943:73)
    at http://172.23.42.86:8081/js/Visualization/src/other/Comms.js:920:25
    at Promise (<anonymous>)
    at HIPIEWorkunit.call (http://172.23.42.86:8081/js/Visualization/src/other/Comms.js:919:20)
    at http://172.23.42.86:8081/js/Visualization/src/marshaller/HipieDDL.js:1706:27
    at Promise (<anonymous>)
    at Datasource.fetchData (http://172.23.42.86:8081/js/Visualization/src/marshaller/HipieDDL.js:1705:16)
    at DatasourceRequestOptimizer.fetchData (http://172.23.42.86:8081/js/Visualization/src/marshaller/HipieDDL.js:1570:49)
    at VisualizationRequestOptimizer.fetchData (http://172.23.42.86:8081/js/Visualization/src/marshaller/HipieDDL.js:1608:43)
    at Event.fetchData (http://172.23.42.86:8081/js/Visualization/src/marshaller/HipieDDL.js:684:35)
    at http://172.23.42.86:8081/js/Visualization/src/marshaller/HipieDDL.js:1348:19
```

DUD:
```
ID "3eea9bc6-5767-4f09-9d48-2d5eb93dce1f";
LABEL rangefilterdemo2dashboard;
NAME rangefilterdemo2dashboard;
AUTHOR woodbr01;
DESCRIPTION "RAMPS - Dashboard Perspective Contract";
CATEGORY VISUALIZE;
VERSION "0.1";
PERMISSIONS
VIEW:PUBLIC;
EDIT:PRIVATE;
RUN:PUBLIC;
END

INPUTS
	DATASET dsInput1: MAPBYNAME,OPTIONAL
	FIELD dsInput1_companyname: LABEL("companyname");
	FIELD dsInput1_turnover: LABEL("turnover");
	FIELD dsInput1_place: LABEL("place");
END
END

OUTPUTS
	DATASET dsOutput1(dsInput1): WUID;
END
VISUALIZE rangefilterdemo2dashboard
	  PIE LessThanPie(dsOutput1{dsInput1_companyname,AVE(dsInput1_turnover)}): LABEL(dsInput1_companyname),WEIGHT(AVE(dsInput1_turnover)),SELECTS(INPUTS.dsInput1_companyname->LessThanTable.companyname,MERGE),FILTER(?<dsInput1_companyname),TITLE("Less Than Pie"), _charttype("AM_PIE");
	  TABLE LessThanTable(dsOutput1{AVE(dsInput1_turnover),COUNT,dsInput1_companyname,dsInput1_place}): LABEL("AVE(turnover)","rowcount","companyname","place"),VALUE(AVE(dsInput1_turnover),COUNT,dsInput1_companyname,dsInput1_place),FILTER(dsInput1_companyname),TITLE("Less Than Table"), _charttype("TABLE");
	  PIE LessThanEqualsPie(dsOutput1{dsInput1_companyname,AVE(dsInput1_turnover)}): LABEL(dsInput1_companyname),WEIGHT(AVE(dsInput1_turnover)),SELECTS(INPUTS.dsInput1_companyname->LessThanEqualsTable.companyname,MERGE),FILTER(?<=dsInput1_companyname),TITLE("Less Than Equals Pie"), _charttype("AM_PIE");
	  TABLE LessThanEqualsTable(dsOutput1{AVE(dsInput1_turnover),COUNT,dsInput1_companyname,dsInput1_place}): LABEL("AVE(turnover)","rowcount","companyname","place"),VALUE(AVE(dsInput1_turnover),COUNT,dsInput1_companyname,dsInput1_place),FILTER(dsInput1_companyname),TITLE("Less Than Equals Table"), _charttype("TABLE");
	  PIE EqualsPie(dsOutput1{dsInput1_companyname,AVE(dsInput1_turnover)}): LABEL(dsInput1_companyname),WEIGHT(AVE(dsInput1_turnover)),SELECTS(INPUTS.dsInput1_companyname->EqualsTable.companyname,MERGE),TITLE("Equals Pie"), _charttype("AM_PIE");
	  TABLE EqualsTable(dsOutput1{AVE(dsInput1_turnover),COUNT,dsInput1_companyname,dsInput1_place}): LABEL("AVE(turnover)","rowcount","companyname","place"),VALUE(AVE(dsInput1_turnover),COUNT,dsInput1_companyname,dsInput1_place),FILTER(dsInput1_companyname),TITLE("Equals Table"), _charttype("TABLE");
	  PIE NotEqualsPie(dsOutput1{dsInput1_companyname,AVE(dsInput1_turnover)}): LABEL(dsInput1_companyname),WEIGHT(AVE(dsInput1_turnover)),SELECTS(INPUTS.dsInput1_companyname->NotEqualsTable.companyname,MERGE),TITLE("Not Equals Pie"), _charttype("AM_PIE");
	  TABLE NotEqualsTable(dsOutput1{AVE(dsInput1_turnover),COUNT,dsInput1_companyname,dsInput1_place}): LABEL("AVE(turnover)","rowcount","companyname","place"),VALUE(AVE(dsInput1_turnover),COUNT,dsInput1_companyname,dsInput1_place),FILTER(dsInput1_companyname),TITLE("Not Equals Table"), _charttype("TABLE");
	  PIE GreaterThanEqualsPie(dsOutput1{dsInput1_companyname,AVE(dsInput1_turnover)}): LABEL(dsInput1_companyname),WEIGHT(AVE(dsInput1_turnover)),SELECTS(INPUTS.dsInput1_companyname->GreaterThanEqualsTable.companyname,MERGE),TITLE("Greater Than Equals Pie"), _charttype("AM_PIE");
	  TABLE GreaterThanEqualsTable(dsOutput1{AVE(dsInput1_turnover),COUNT,dsInput1_companyname,dsInput1_place}): LABEL("AVE(turnover)","rowcount","companyname","place"),VALUE(AVE(dsInput1_turnover),COUNT,dsInput1_companyname,dsInput1_place),FILTER(dsInput1_companyname),TITLE("Greater Than Equals Table"), _charttype("TABLE");
	  PIE GreaterThanPie(dsOutput1{dsInput1_companyname,AVE(dsInput1_turnover)}): LABEL(dsInput1_companyname),WEIGHT(AVE(dsInput1_turnover)),SELECTS(INPUTS.dsInput1_companyname->GreaterThanTable.companyname,MERGE),TITLE("Greater Than Pie"), _charttype("AM_PIE");
	  TABLE GreaterThanTable(dsOutput1{AVE(dsInput1_turnover),COUNT,dsInput1_companyname,dsInput1_place}): LABEL("AVE(turnover)","rowcount","companyname","place"),VALUE(AVE(dsInput1_turnover),COUNT,dsInput1_companyname,dsInput1_place),FILTER(dsInput1_companyname),TITLE("Greater Than Table"), _charttype("TABLE");
	  

        FORM LocalFilterFORM: TITLE("Local Filter"),SELECTS(*->LocalFilter), _flyout(true),_allowEmptyRequest(true)
	    STRING place: LABEL("place"),DEFAULT("Kansas");
        END
	  TABLE LocalFilter(dsOutput1{AVE(dsInput1_turnover),COUNT,dsInput1_companyname,dsInput1_place}): LABEL("AVE(turnover)","rowcount","companyname","place"),VALUE(AVE(dsInput1_turnover),COUNT,dsInput1_companyname,dsInput1_place),FILTER(dsInput1_place),TITLE("Local Filter"), _charttype("TABLE");
END
```

CMP:
```
ID "8fbbca0d-b6b6-45a1-951c-f94183d3f06f";
NAME rangefilterdemo2;
LABEL RangeFilterDemo2;
CATEGORY VISUALIZE;
DESCRIPTION "DSP Generated Dashboard Composition";
VERSION "1.0.0";
AUTHOR woodbr01;
PERMISSIONS
VIEW:PRIVATE;
EDIT:PRIVATE;
RUN:PRIVATE;
END

INPUTS
	STRING VIZSERVICEVERSION: LABEL("Visualization Service Version"),DEFAULT("1"),OPTIONAL;
	STRING GCID: LABEL("GLOBAL COMPANY ID"),DEFAULT(0);
	STRING JOBID: LABEL("Job ID"),DEFAULT("0");
	STRING InputLogicalFilename: LABEL("Input Logical Filename"),DEFAULT("~temp::in");
END
INSTANCE dashboardrepo.woodbr01dashboardduds.rangefilterdemo2dashboard(Ins4669119)
	dsInput1_companyname="companyname"
	dsInput1_turnover="turnover"
	dsInput1_place="place"
	dsInput1="^Ins4669118|dsOutput"
	_MODE="ADVANCED"
END
INSTANCE hipie_plugins.UseDataset.UseDataset(Ins4669118)
	Structure="{ string companyname, integer8 turnover, string place };
"
	LogicalFilename="~.a::valid_file"
	Method="THOR"
END
```

DDL:
```
{
	"dashboards": [{
		"id": "Ins4669119_rangefilterdemo2dashboard",
		"label": "rangefilterdemo2dashboard",
		"title": "rangefilterdemo2dashboard",
		"visualizations": [{
			"events": {
				"click": {
					"updates": [{
						"datasource": "Ins4669119_dsOutput1",
						"instance": "Ins4669119",
						"mappings": {
							"companyname": "companyname"
						},
						"merge": true,
						"visualization": "LessThanTable"
					}]
				}
			},
			"fields": [{
				"id": "companyname",
				"properties": {
					"datatype": "string",
					"type": "string"
				}
			}, {
				"id": "turnover_AVE",
				"properties": {
					"datatype": "real",
					"function": "AVE",
					"params": {
						"param1": "turnover_SUM",
						"param2": "Base_COUNT"
					},
					"type": "real"
				}
			}],
			"id": "LessThanPie",
			"properties": {
				"charttype": "AM_PIE"
			},
			"source": {
				"id": "Ins4669119_dsOutput1",
				"mappings": {
					"label": "companyname",
					"weight": ["turnover_AVE"]
				},
				"output": "View_LessThanPie"
			},
			"title": "Less Than Pie",
			"type": "PIE"
		}, {
			"fields": [{
				"id": "turnover_AVE",
				"properties": {
					"datatype": "real",
					"function": "AVE",
					"label": "AVE(turnover)",
					"params": {
						"param1": "turnover_SUM",
						"param2": "Base_COUNT"
					},
					"type": "real"
				}
			}, {
				"id": "Base_COUNT",
				"properties": {
					"datatype": "integer",
					"function": "SUM",
					"label": "rowcount",
					"params": {
						"param1": "Base_COUNT"
					},
					"type": "integer"
				}
			}, {
				"id": "companyname",
				"properties": {
					"datatype": "string",
					"label": "companyname",
					"type": "string"
				}
			}, {
				"id": "place",
				"properties": {
					"datatype": "string",
					"label": "place",
					"type": "string"
				}
			}],
			"id": "LessThanTable",
			"label": ["AVE(turnover)", "rowcount", "companyname", "place"],
			"properties": {
				"charttype": "TABLE"
			},
			"source": {
				"id": "Ins4669119_dsOutput1",
				"mappings": {
					"value": ["turnover_AVE", "Base_COUNT", "companyname", "place"]
				},
				"output": "View_LessThanTable"
			},
			"title": "Less Than Table",
			"type": "TABLE"
		}, {
			"events": {
				"click": {
					"updates": [{
						"datasource": "Ins4669119_dsOutput1",
						"instance": "Ins4669119",
						"mappings": {
							"companyname": "companyname"
						},
						"merge": true,
						"visualization": "LessThanEqualsTable"
					}]
				}
			},
			"fields": [{
				"id": "companyname",
				"properties": {
					"datatype": "string",
					"type": "string"
				}
			}, {
				"id": "turnover_AVE",
				"properties": {
					"datatype": "real",
					"function": "AVE",
					"params": {
						"param1": "turnover_SUM",
						"param2": "Base_COUNT"
					},
					"type": "real"
				}
			}],
			"id": "LessThanEqualsPie",
			"properties": {
				"charttype": "AM_PIE"
			},
			"source": {
				"id": "Ins4669119_dsOutput1",
				"mappings": {
					"label": "companyname",
					"weight": ["turnover_AVE"]
				},
				"output": "View_LessThanEqualsPie"
			},
			"title": "Less Than Equals Pie",
			"type": "PIE"
		}, {
			"fields": [{
				"id": "turnover_AVE",
				"properties": {
					"datatype": "real",
					"function": "AVE",
					"label": "AVE(turnover)",
					"params": {
						"param1": "turnover_SUM",
						"param2": "Base_COUNT"
					},
					"type": "real"
				}
			}, {
				"id": "Base_COUNT",
				"properties": {
					"datatype": "integer",
					"function": "SUM",
					"label": "rowcount",
					"params": {
						"param1": "Base_COUNT"
					},
					"type": "integer"
				}
			}, {
				"id": "companyname",
				"properties": {
					"datatype": "string",
					"label": "companyname",
					"type": "string"
				}
			}, {
				"id": "place",
				"properties": {
					"datatype": "string",
					"label": "place",
					"type": "string"
				}
			}],
			"id": "LessThanEqualsTable",
			"label": ["AVE(turnover)", "rowcount", "companyname", "place"],
			"properties": {
				"charttype": "TABLE"
			},
			"source": {
				"id": "Ins4669119_dsOutput1",
				"mappings": {
					"value": ["turnover_AVE", "Base_COUNT", "companyname", "place"]
				},
				"output": "View_LessThanTable"
			},
			"title": "Less Than Equals Table",
			"type": "TABLE"
		}, {
			"events": {
				"click": {
					"updates": [{
						"datasource": "Ins4669119_dsOutput1",
						"instance": "Ins4669119",
						"mappings": {
							"companyname": "companyname"
						},
						"merge": true,
						"visualization": "EqualsTable"
					}]
				}
			},
			"fields": [{
				"id": "companyname",
				"properties": {
					"datatype": "string",
					"type": "string"
				}
			}, {
				"id": "turnover_AVE",
				"properties": {
					"datatype": "real",
					"function": "AVE",
					"params": {
						"param1": "turnover_SUM",
						"param2": "Base_COUNT"
					},
					"type": "real"
				}
			}],
			"id": "EqualsPie",
			"properties": {
				"charttype": "AM_PIE"
			},
			"source": {
				"id": "Ins4669119_dsOutput1",
				"mappings": {
					"label": "companyname",
					"weight": ["turnover_AVE"]
				},
				"output": "View_EqualsPie"
			},
			"title": "Equals Pie",
			"type": "PIE"
		}, {
			"fields": [{
				"id": "turnover_AVE",
				"properties": {
					"datatype": "real",
					"function": "AVE",
					"label": "AVE(turnover)",
					"params": {
						"param1": "turnover_SUM",
						"param2": "Base_COUNT"
					},
					"type": "real"
				}
			}, {
				"id": "Base_COUNT",
				"properties": {
					"datatype": "integer",
					"function": "SUM",
					"label": "rowcount",
					"params": {
						"param1": "Base_COUNT"
					},
					"type": "integer"
				}
			}, {
				"id": "companyname",
				"properties": {
					"datatype": "string",
					"label": "companyname",
					"type": "string"
				}
			}, {
				"id": "place",
				"properties": {
					"datatype": "string",
					"label": "place",
					"type": "string"
				}
			}],
			"id": "EqualsTable",
			"label": ["AVE(turnover)", "rowcount", "companyname", "place"],
			"properties": {
				"charttype": "TABLE"
			},
			"source": {
				"id": "Ins4669119_dsOutput1",
				"mappings": {
					"value": ["turnover_AVE", "Base_COUNT", "companyname", "place"]
				},
				"output": "View_LessThanTable"
			},
			"title": "Equals Table",
			"type": "TABLE"
		}, {
			"events": {
				"click": {
					"updates": [{
						"datasource": "Ins4669119_dsOutput1",
						"instance": "Ins4669119",
						"mappings": {
							"companyname": "companyname"
						},
						"merge": true,
						"visualization": "NotEqualsTable"
					}]
				}
			},
			"fields": [{
				"id": "companyname",
				"properties": {
					"datatype": "string",
					"type": "string"
				}
			}, {
				"id": "turnover_AVE",
				"properties": {
					"datatype": "real",
					"function": "AVE",
					"params": {
						"param1": "turnover_SUM",
						"param2": "Base_COUNT"
					},
					"type": "real"
				}
			}],
			"id": "NotEqualsPie",
			"properties": {
				"charttype": "AM_PIE"
			},
			"source": {
				"id": "Ins4669119_dsOutput1",
				"mappings": {
					"label": "companyname",
					"weight": ["turnover_AVE"]
				},
				"output": "View_EqualsPie"
			},
			"title": "Not Equals Pie",
			"type": "PIE"
		}, {
			"fields": [{
				"id": "turnover_AVE",
				"properties": {
					"datatype": "real",
					"function": "AVE",
					"label": "AVE(turnover)",
					"params": {
						"param1": "turnover_SUM",
						"param2": "Base_COUNT"
					},
					"type": "real"
				}
			}, {
				"id": "Base_COUNT",
				"properties": {
					"datatype": "integer",
					"function": "SUM",
					"label": "rowcount",
					"params": {
						"param1": "Base_COUNT"
					},
					"type": "integer"
				}
			}, {
				"id": "companyname",
				"properties": {
					"datatype": "string",
					"label": "companyname",
					"type": "string"
				}
			}, {
				"id": "place",
				"properties": {
					"datatype": "string",
					"label": "place",
					"type": "string"
				}
			}],
			"id": "NotEqualsTable",
			"label": ["AVE(turnover)", "rowcount", "companyname", "place"],
			"properties": {
				"charttype": "TABLE"
			},
			"source": {
				"id": "Ins4669119_dsOutput1",
				"mappings": {
					"value": ["turnover_AVE", "Base_COUNT", "companyname", "place"]
				},
				"output": "View_LessThanTable"
			},
			"title": "Not Equals Table",
			"type": "TABLE"
		}, {
			"events": {
				"click": {
					"updates": [{
						"datasource": "Ins4669119_dsOutput1",
						"instance": "Ins4669119",
						"mappings": {
							"companyname": "companyname"
						},
						"merge": true,
						"visualization": "GreaterThanEqualsTable"
					}]
				}
			},
			"fields": [{
				"id": "companyname",
				"properties": {
					"datatype": "string",
					"type": "string"
				}
			}, {
				"id": "turnover_AVE",
				"properties": {
					"datatype": "real",
					"function": "AVE",
					"params": {
						"param1": "turnover_SUM",
						"param2": "Base_COUNT"
					},
					"type": "real"
				}
			}],
			"id": "GreaterThanEqualsPie",
			"properties": {
				"charttype": "AM_PIE"
			},
			"source": {
				"id": "Ins4669119_dsOutput1",
				"mappings": {
					"label": "companyname",
					"weight": ["turnover_AVE"]
				},
				"output": "View_EqualsPie"
			},
			"title": "Greater Than Equals Pie",
			"type": "PIE"
		}, {
			"fields": [{
				"id": "turnover_AVE",
				"properties": {
					"datatype": "real",
					"function": "AVE",
					"label": "AVE(turnover)",
					"params": {
						"param1": "turnover_SUM",
						"param2": "Base_COUNT"
					},
					"type": "real"
				}
			}, {
				"id": "Base_COUNT",
				"properties": {
					"datatype": "integer",
					"function": "SUM",
					"label": "rowcount",
					"params": {
						"param1": "Base_COUNT"
					},
					"type": "integer"
				}
			}, {
				"id": "companyname",
				"properties": {
					"datatype": "string",
					"label": "companyname",
					"type": "string"
				}
			}, {
				"id": "place",
				"properties": {
					"datatype": "string",
					"label": "place",
					"type": "string"
				}
			}],
			"id": "GreaterThanEqualsTable",
			"label": ["AVE(turnover)", "rowcount", "companyname", "place"],
			"properties": {
				"charttype": "TABLE"
			},
			"source": {
				"id": "Ins4669119_dsOutput1",
				"mappings": {
					"value": ["turnover_AVE", "Base_COUNT", "companyname", "place"]
				},
				"output": "View_LessThanTable"
			},
			"title": "Greater Than Equals Table",
			"type": "TABLE"
		}, {
			"events": {
				"click": {
					"updates": [{
						"datasource": "Ins4669119_dsOutput1",
						"instance": "Ins4669119",
						"mappings": {
							"companyname": "companyname"
						},
						"merge": true,
						"visualization": "GreaterThanTable"
					}]
				}
			},
			"fields": [{
				"id": "companyname",
				"properties": {
					"datatype": "string",
					"type": "string"
				}
			}, {
				"id": "turnover_AVE",
				"properties": {
					"datatype": "real",
					"function": "AVE",
					"params": {
						"param1": "turnover_SUM",
						"param2": "Base_COUNT"
					},
					"type": "real"
				}
			}],
			"id": "GreaterThanPie",
			"properties": {
				"charttype": "AM_PIE"
			},
			"source": {
				"id": "Ins4669119_dsOutput1",
				"mappings": {
					"label": "companyname",
					"weight": ["turnover_AVE"]
				},
				"output": "View_EqualsPie"
			},
			"title": "Greater Than Pie",
			"type": "PIE"
		}, {
			"fields": [{
				"id": "turnover_AVE",
				"properties": {
					"datatype": "real",
					"function": "AVE",
					"label": "AVE(turnover)",
					"params": {
						"param1": "turnover_SUM",
						"param2": "Base_COUNT"
					},
					"type": "real"
				}
			}, {
				"id": "Base_COUNT",
				"properties": {
					"datatype": "integer",
					"function": "SUM",
					"label": "rowcount",
					"params": {
						"param1": "Base_COUNT"
					},
					"type": "integer"
				}
			}, {
				"id": "companyname",
				"properties": {
					"datatype": "string",
					"label": "companyname",
					"type": "string"
				}
			}, {
				"id": "place",
				"properties": {
					"datatype": "string",
					"label": "place",
					"type": "string"
				}
			}],
			"id": "GreaterThanTable",
			"label": ["AVE(turnover)", "rowcount", "companyname", "place"],
			"properties": {
				"charttype": "TABLE"
			},
			"source": {
				"id": "Ins4669119_dsOutput1",
				"mappings": {
					"value": ["turnover_AVE", "Base_COUNT", "companyname", "place"]
				},
				"output": "View_LessThanTable"
			},
			"title": "Greater Than Table",
			"type": "TABLE"
		}, {
			"events": {
				"click": {
					"updates": [{
						"datasource": "Ins4669119_dsOutput1",
						"instance": "Ins4669119",
						"mappings": {
							"place": "place"
						},
						"merge": false,
						"visualization": "LocalFilter"
					}]
				}
			},
			"fields": [{
				"id": "place",
				"properties": {
					"datatype": "string",
					"default": ["Kansas"],
					"label": "place",
					"type": "string"
				}
			}],
			"id": "LocalFilterFORM",
			"properties": {
				"allowEmptyRequest": true,
				"flyout": true
			},
			"title": "Local Filter",
			"type": "FORM"
		}, {
			"fields": [{
				"id": "turnover_AVE",
				"properties": {
					"datatype": "real",
					"function": "AVE",
					"label": "AVE(turnover)",
					"params": {
						"param1": "turnover_SUM",
						"param2": "Base_COUNT"
					},
					"type": "real"
				}
			}, {
				"id": "Base_COUNT",
				"properties": {
					"datatype": "integer",
					"function": "SUM",
					"label": "rowcount",
					"params": {
						"param1": "Base_COUNT"
					},
					"type": "integer"
				}
			}, {
				"id": "companyname",
				"properties": {
					"datatype": "string",
					"label": "companyname",
					"type": "string"
				}
			}, {
				"id": "place",
				"properties": {
					"datatype": "string",
					"label": "place",
					"type": "string"
				}
			}],
			"id": "LocalFilter",
			"label": ["AVE(turnover)", "rowcount", "companyname", "place"],
			"properties": {
				"charttype": "TABLE"
			},
			"source": {
				"id": "Ins4669119_dsOutput1",
				"mappings": {
					"value": ["turnover_AVE", "Base_COUNT", "companyname", "place"]
				},
				"output": "View_LocalFilter"
			},
			"title": "Local Filter",
			"type": "TABLE"
		}]
	}],
	"datasources": [{
		"WUID": true,
		"filter": [{
			"fieldid": "companyname",
			"nullable": false,
			"rule": "<"
		}, {
			"fieldid": "place",
			"nullable": false,
			"rule": "=="
		}],
		"id": "Ins4669119_dsOutput1",
		"outputs": [{
			"filter": [{
				"fieldid": "companyname",
				"nullable": true,
				"rule": "<"
			}],
			"from": "Ins4669119_dsOutput1_View_LessThanPie",
			"id": "View_LessThanPie",
			"notify": ["LessThanPie"]
		}, {
			"filter": [{
				"fieldid": "companyname",
				"nullable": false,
				"rule": "=="
			}],
			"from": "Ins4669119_dsOutput1_View_LessThanTable",
			"id": "View_LessThanTable",
			"notify": ["LessThanTable", "LessThanEqualsTable", "EqualsTable", "NotEqualsTable", "GreaterThanEqualsTable", "GreaterThanTable"]
		}, {
			"filter": [{
				"fieldid": "companyname",
				"nullable": true,
				"rule": "<="
			}],
			"from": "Ins4669119_dsOutput1_View_LessThanEqualsPie",
			"id": "View_LessThanEqualsPie",
			"notify": ["LessThanEqualsPie"]
		}, {
			"from": "Ins4669119_dsOutput1_View_EqualsPie",
			"id": "View_EqualsPie",
			"notify": ["EqualsPie", "NotEqualsPie", "GreaterThanEqualsPie", "GreaterThanPie"]
		}, {
			"filter": [{
				"fieldid": "place",
				"nullable": false,
				"rule": "=="
			}],
			"from": "Ins4669119_dsOutput1_View_LocalFilter",
			"id": "View_LocalFilter",
			"notify": ["LocalFilter"]
		}]
	}],
	"hipieversion": "1.9.0-rc1",
	"visualizationversion": "v1.16.0-beta4"
}
```

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
